### ISSUE TITLE
binary data dimension mis-match

### ISSUE THREAD

**Issue by cuih0001** [Haifafh/MFAT#1]
binary data dimension mis-match

Error FractionalIstropicTensor3D (line 55)
    response(x == max(x(:,:,:))) = 1;

Error FAT_test_3D (line 30)
iout1 = FractionalIstropicTensor3D(I,sigmas,tau,tau2,D,spacing,whiteondark);

Hi, when I run the test code for 3D case, I got the above error. Maybe it is data dimension mis-match. Could you please help to check. Thank you very much.

**Comment by Haifafh** [comment]
Hi,
I checked it out for you, the code is correct.
Thanks
